### ISSUE TITLE
panic on aws scraper

### ISSUE THREAD

**Issue by adityathebe** [flanksource/config-db#887]
```
10:48:35.046 DBG (default/aws-adityathebe) Starting scraper
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6a2c305]

goroutine 78079 [running]:
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.deferwrap1()
        /home/aditya/.local/share/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.24.0/trace/span.go:405 +0x2e
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc00342b980, {0x0, 0x0, 0x0})
        /home/aditya/.local/share/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.24.0/trace/span.go:443 +0xae5
panic({0xbba7940?, 0x1011fa60?})
        /usr/lib/go/src/runtime/panic.go:785 +0x136
github.com/flanksource/duty/connection.(*AWSConnection).Populate(0xc005c1c180, {0xd255790, 0xc000b2e460})
        /home/aditya/.local/share/go/pkg/mod/github.com/flanksource/duty@v1.0.611/connection/aws.go:74 +0x245
github.com/flanksource/config-db/scrapers/aws.Scraper.getContext({}, {{{{0xd246018, 0xc006ade120}, {0xd2796d0, 0xc006ade0c0}, 0xca9d398, 0xca9d3a0, {0xd212918, 0xc000d93db0}}}, 0xc002c340a8, ...}, ...)
        /home/aditya/projects/flanksource/config-db/scrapers/aws/aws.go:79 +0xb9
github.com/flanksource/config-db/scrapers/aws.Scraper.Scrape({}, {{{{0xd246018, 0xc006ade120}, {0xd2796d0, 0xc006ade0c0}, 0xca9d398, 0xca9d3a0, {0xd212918, 0xc000d93db0}}}, 0xc002c340a8, ...})
        /home/aditya/projects/flanksource/config-db/scrapers/aws/aws.go:1733 +0x3c5
github.com/flanksource/config-db/scrapers.Run({{{{0xd246018, 0xc006ade120}, {0xd2796d0, 0xc006ade0c0}, 0xca9d398, 0xca9d3a0, {0xd212918, 0xc000d93db0}}}, 0xc002c340a8, {0x0, ...}, ...})
        /home/aditya/projects/flanksource/config-db/scrapers/runscrapers.go:54 +0x25d
github.com/flanksource/config-db/scrapers.RunScraper({{{{0xd246018, 0xc006ade120}, {0xd2796d0, 0xc006ade0c0}, 0xca9d398, 0xca9d3a0, {0xd212918, 0xc000d93db0}}}, 0xc002c340a8, {0x0, ...}, ...})
        /home/aditya/projects/flanksource/config-db/scrapers/run.go:36 +0x778
github.com/flanksource/config-db/scrapers.newScraperJob.func1({{{{0xd246018, 0xc00812d860}, {0xd2796d0, 0xc00812d890}, 0xca9d398, 0xca9d3a0, {0xd212918, 0xc000d93db0}}}, 0xc000d64000, {0xd25d178, ...}, ...})
        /home/aditya/projects/flanksource/config-db/scrapers/cron.go:208 +0xf9
github.com/flanksource/duty/job.(*Job).Run(0xc000d64000)
        /home/aditya/.local/share/go/pkg/mod/github.com/flanksource/duty@v1.0.611/job/job.go:393 +0x1b5a
github.com/robfig/cron/v3.(*Cron).startJob.func1()
        /home/aditya/.local/share/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0xad
created by github.com/robfig/cron/v3.(*Cron).startJob in goroutine 178
        /home/aditya/.local/share/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xc6

```

**Comment by adityathebe** [comment]
This was on old duty version duty@v1.0.611

**Comment by adityathebe** [comment]
resolved by: https://github.com/flanksource/config-db/pull/910
